import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import Toast from "./Toaster";

const inter = Outfit({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app2",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toast>{children}</Toast>
      </body>
    </html>
  );
}
